apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bike-weather.yaml
  - bike-weather-auth.yaml
  - bike-weather-preview.yaml
  - bike-weather-http-redirect.yaml
  - givgroov.yaml
  - mealie.yaml
  - open-webui.yaml
  - portfolio.yaml
