apiVersion: v1
kind: ConfigMap
metadata:
  name: vinyl-manager-config
  namespace: vinyl-manager
data:
  # Backend configuration
  ENV: "production"
  AUDIO_ANALYZER_URL: "http://vinyl-audio-analyzer:5000"
  # Frontend configuration
  API_URL: "http://vinyl-backend:8000"
