apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC

    [server]
    domain = grafana.timosur.com

    [database]
    type = postgres
    host = grafana-postgres-rw.monitoring.svc.cluster.local:5432
    name = grafana
    user = grafana
    password = $__env{GF_DATABASE_PASSWORD}
    ssl_mode = disable

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
type: Opaque