apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml
- postgres-external-secret.yaml
- grafana-config-secret.yaml

patchesStrategicMerge:
- grafana-config-secret.yaml
- grafana-deployment-patch.yaml