apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - garden-httproute.yaml
  - argocd-httproute.yaml
  - vinyl-manager-httproute.yaml
  - home-assistant-httproute.yaml
  - pi-hole-httproute.yaml
  - open-webui-internet-httproute.yaml
  - paperless-httproute.yaml
  - actual-httproute.yaml
  - givgroov-httproute.yaml
  - portfolio-httproute.yaml
  - mealie-httproute.yaml
