apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bike-weather

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - postgres-external-secret.yaml
  - postgres-password-secret.yaml
  - postgres.yaml
  - nginx-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
