apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - envoy-gateway-home.yaml
  - envoy-gateway-internet-namespace.yaml
  - envoy-gateway-internet.yaml
  - wildcard-certificate.yaml
  - givgroov-certificate.yaml
  - http-to-https-redirect.yaml
