apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-backend-config
  namespace: garden
data:
  TZ: "Europe/Berlin"
  PYTHONPATH: /app
  PYTHONUNBUFFERED: "1"
  FRONTEND_URL: http://garden-nginx:80
  RMAPI_SERVICE_URL: http://garden-rmapi-wrapper:8001
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  NOTIFICATION_EMAIL: lebensgarten@timosur.com
  EMAIL_NOTIFICATIONS_ENABLED: "true"
  # Database configuration
  DB_HOST: garden-postgres-rw
  DB_PORT: "5432"
  DB_NAME: garden
  DB_USER: garden
