apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garden

resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-external-secret.yaml
  - rmapi-external-secret.yaml
  - postgres.yaml
  - postgres-external-secret.yaml
  - postgres-password-secret.yaml
  - nginx-auth-configmap.yaml
  - nginx-auth-external-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - rmapi-wrapper-deployment.yaml
  - rmapi-wrapper-service.yaml
  - nginx-auth-deployment.yaml
  - nginx-auth-service.yaml
  - scheduler-cronjob.yaml
  - backup-cronjob.yaml
