apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-route.yaml
  - mealie-route.yaml
  - ai-route.yaml
  - garden-route.yaml
  - seafile-route.yaml
  - portfolio-route.yaml
  - givgroov-route.yaml
  - actual-route.yaml
  - docs-route.yaml
