apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bike-weather-auth

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - postgres-external-secret.yaml
  - postgres.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - worker-deployment.yaml
  - media-pvc.yaml
  - email-templates-configmap.yaml
