apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - actual.yaml
  - argocd.yaml
  - garden.yaml
  - home-assistant.yaml
  - paperless.yaml
  - pi-hole.yaml
  - vinyl-manager.yaml
