apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-home-app.yaml
  - cloudnative-pg-app.yaml
  - envoy-gateway-app.yaml
  - external-secrets-app.yaml
  - garden-app.yaml
  - networking-home-app.yaml
  - open-webui-home-app.yaml
  - smb-csi-driver-app.yaml
  - synology-csi-driver-app.yaml
  - vinyl-manager-app.yaml
  - home-assistant-app.yaml
  - pi-hole-app.yaml
