apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudnative-pg-app.yaml
  - envoy-gateway-app.yaml
  - external-secrets-app.yaml
  - garden-app.yaml
  - smb-csi-driver-app.yaml
