apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc

  patchesJson6902:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: grafana
        namespace: monitoring
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: GF_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-postgres-credentials
                key: password

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana-config
      namespace: monitoring
      jsonPointers:
        - /data/grafana.ini
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  info:
    - name: Dependencies
      value: "Requires kube-prometheus-setup to be deployed first"