apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bike-weather-app.yaml
  - bike-weather-auth-app.yaml
  - bike-weather-preview-app.yaml
  - cert-manager-app.yaml
  - cloudnative-pg-app.yaml
  - envoy-gateway-app.yaml
  - external-secrets-app.yaml
  - garden-app.yaml
  - networking-app.yaml
  - open-webui-app.yaml
  - smb-csi-driver-app.yaml
  - synology-csi-driver-app.yaml
  - vinyl-manager-app.yaml
  - actual-app.yaml
  - givgroov-app.yaml
  - home-assistant-app.yaml
  - mealie-app.yaml
  - paperless-app.yaml
  - pi-hole-app.yaml
  - portfolio-app.yaml
  - trivy-operator-app.yaml
