apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networking-app.yaml
  - cert-manager-app.yaml
  - external-secrets-app.yaml
  - cloudnative-pg-app.yaml
  - smb-csi-driver-app.yaml
  - storage-box-smb-app.yaml
  - envoy-gateway-app.yaml
  - mealie-app.yaml
  - open-webui-app.yaml
  - garden-app.yaml
  - seafile-app.yaml
  - portfolio-app.yaml
  - givgroov-app.yaml
  - actual-app.yaml
  - paperless-app.yaml
