apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

resources:
  - namespace.yaml
  - redis-configmap.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - postgres.yaml
  - external-secret.yaml
  - ollama-statefulset.yaml
  - ollama-service.yaml
  - webui-deployment.yaml
  - webui-pvc.yaml
  - webui-service.yaml
